
	$.confs=new Array();
	
	$.confs['date_yearMin']=					'1900';
	$.confs['date_yearMax']=					'2300';
	$.confs['date_format']=						'%M %Y-%m-%d';
	$.confs['password-strength-min-length']=	'10';
	
	$.confs['noty-max']=						'5';
	$.confs['noty-position']=					'top-left';
	
	$.langs=new Array();	
	
	$.langs['gallery-views']=					'View #1 of #2 Image(s)';
	$.langs['gallery-print']=					'Print Image';
	$.langs['gallery-reset']=					'RESET';
	$.langs['gallery-limit']=					'LIMIT';
	
	$.langs['date-short-week-days']=			'Sun,Mon,Tue,Wed,Thu,Fri,Sat';
	$.langs['date-full-week-days']=				'Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday';
	$.langs['date-full-month-names']=			'January,February,March,April,May,June,July,August,September,October,November,December';
	$.langs['date-short-month-names']=			'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec';
	
	$.langs['confirm-yes']=						'Yes';
	$.langs['confirm-ok']=						'OK';
	$.langs['confirm-cancel']=					'Cancel';
	$.langs['confirm-no']=						'No';
	
	$.langs['select-all-selected']=				'All {0} Selected!';
	$.langs['select-selected']=					'{0} Selected!';
	$.langs['select-here']=						'Select Here';
	
	$(document).ready(function(){
		$('body').find('.gallery')				.each(function()	{	$(this).elements();	});		
		$('body').find('tab')					.each(function()	{	$(this).elements();	});
		$('body').find('textarea.editor')		.each(function()	{	$(this).elements();	});
		$('body').find('input')					.each(function()	{	$(this).elements();	});
		$('body').find('select')				.each(function()	{	$(this).elements();	});
		$('body').find('.accordion')			.each(function()	{	$(this).elements();	});
    });
	
	/****************************************/
	/** FUNCTIONS		**  CORE			*/	var core={
	/**					**					*/		isMobile:							function() 							{	if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)){return true;}else{return false;} }
	/**					**					*/	}
	/**					***************************************************************/
	/**					**	COLORS			*/	var colors={
	/**					**					*/		color:								'',
	/**					**					*/		static:								'',
	/**					**					*/		colors:								['#000000','#444444','#666666','#999999','#cccccc','#eeeeee','#f3f3f3','#ffffff','#ff0000','#ff9900','#ffff00','#00ff00','#00ffff','#0000ff','#9900ff','#ff00ff','#f4cccc','#fce5cd','#fff2cc','#d9ead3','#d0e0e3','#cfe2f3','#d9d2e9','#ead1dc','#ea9999','#f9cb9c','#ffe599','#b6d7a8','#a2c4c9','#9fc5e8','#b4a7d6','#d5a6bd','#e06666','#f6b26b','#ffd966','#93c47d','#76a5af','#6fa8dc','#8e7cc3','#c27ba0','#cc0000','#e69138','#f1c232','#6aa84f','#45818e','#3d85c6','#674ea7','#a64d79','#990000','#b45f06','#bf9000','#38761d','#134f5c','#0b5394','#351c75','#741b47','#660000','#783f04','#7f6000','#274e13','#0c343d','#073763','#20124d','#4C1130'],
	/**					**					*/		init:								function(opts)						{	var col=opts.color;if(colors.isValidColor(col)==false)colors.color='#000000';colors.staticColors();box.block('<div id="colorBox">'+'<div class="top">'+'<div class="color"></div>'+'<div class="wheel"></div>'+'<div class="overlay"></div>'+'<div class="h-marker marker"></div>'+'<div class="sl-marker marker"></div>'+'</div>'+'<div class="boxColors">'+colors.static+'</div>'+'<div class="bottom">'+'<div class="preview"></div>'+'<div class="check fa fa-check"></div>'+'<div class="cancel fa fa-times"></div>'+'</div>'+'</div>');colors.events(col,opts); },
	/**					**					*/		events:								function(col,opts)					{	colors.wheel=$('.wheel',$('.box')).get(0);colors.e=$('#colorBox').find('.top');$('*',colors.e).mousedown(colors.mousedown);$('#colorBox').find('.colBox').each(function(){$(this).click(function(){colors.setColor($(this).data('color'));});});$('#colorBox').find('.check').click(function(){opts.callback(colors.color);box.close();});$('#colorBox').find('.cancel').click(function(){box.close();});colors.setColor(col==''||col=='undefined'?'#000000':col); },
	/**					**					*/		staticColors:						function()							{	colors.static='';for(z=0;z<colors.colors.length;z++){colors.static+='<div class="colBox" data-color="'+colors.colors[z]+'" style="background:'+colors.colors[z]+'"></div>';} },
	/**					**					*/		mousedown:							function(event) 					{	if(!document.dragging){$(document).bind('mousemove',colors.mousemove).bind('mouseup',colors.mouseup);document.dragging=true;}var pos=colors.widgetCoords(event);colors.circleDrag=Math.max(Math.abs(pos.x),Math.abs(pos.y))*2>100;colors.mousemove(event);return false; },
	/**					**					*/		mouseup:							function() 							{	$(document).unbind('mousemove',colors.mousemove);$(document).unbind('mouseup',colors.mouseup);document.dragging=false; },
	/**					**					*/		mousemove:							function(event) 					{	var pos=colors.widgetCoords(event);if(colors.circleDrag){var hue=Math.atan2(pos.x,-pos.y)/6.28;if(hue<0)hue+=1;colors.setHSL([hue,colors.hsl[1],colors.hsl[2]]);}else{var sat=Math.max(0,Math.min(1,-(pos.x/100)+.5)),lum=Math.max(0,Math.min(1,-(pos.y/100)+.5));colors.setHSL([colors.hsl[0],sat,lum]);}return false; },
	/**					**					*/		widgetCoords:			 			function(event)						{	var x,y,el=event.target||event.srcElement,reference=colors.wheel;if(typeof event.offsetX!='undefined'){var pos={x:event.offsetX,y:event.offsetY},e=el;while(e){e.mouseX=pos.x;e.mouseY=pos.y;pos.x+=e.offsetLeft;pos.y+=e.offsetTop;e=e.offsetParent;}var e=reference,offset={x:0,y:0};while(e){if(typeof e.mouseX!='undefined'){x=e.mouseX-offset.x;y=e.mouseY-offset.y;break;}offset.x+=e.offsetLeft;offset.y+=e.offsetTop;e=e.offsetParent;}e=el;while(e){e.mouseX=undefined;e.mouseY=undefined;e=e.offsetParent;}}else{var pos=colors.abPosition(reference);x=(event.pageX||0*(event.clientX+$('html').get(0).scrollLeft))-pos.x;y=(event.pageY||0*(event.clientY+$('html').get(0).scrollTop))-pos.y;}return{x:x-194/2,y:y-194/2}; },
	/**					**					*/		unpack:								function(col) 						{	if(col.length==7){return[parseInt('0x'+col.substring(1,3))/255,parseInt('0x'+col.substring(3,5))/255,parseInt('0x'+col.substring(5,7))/255];}else if(col.length==4){return[parseInt('0x'+col.substring(1,2))/15,parseInt('0x'+col.substring(2,3))/15,parseInt('0x'+col.substring(3,4))/15];} },
	/**					**					*/		RGBToHSL:							function(rgb) 						{	var min,max,delta,h,s,l,r=rgb[0],g=rgb[1],b=rgb[2];min=Math.min(r,Math.min(g,b));max=Math.max(r,Math.max(g,b));delta=max-min;l=(min+max)/2;s=0;if(l>0&&l<1){s=delta/(l<0.5?(2*l):(2-2*l));}h=0;if(delta>0){if(max==r&&max!=g)h+=(g-b)/delta;if(max==g&&max!=b)h+=(2+(b-r)/delta);if(max==b&&max!=r)h+=(4+(r-g)/delta);h/=6;}return[h,s,l]; },
	/**					**					*/		setColor:							function(col) 						{	var unpack=colors.unpack(col);if(colors.color!=col&&unpack){colors.color=col;colors.rgb=unpack;colors.hsl=colors.RGBToHSL(colors.rgb);colors.updateDisplay();} },
	/**					**					*/		isValidColor:						function(str) 						{	return str.match(/^#[a-f0-9]{6}$/i)!==null; },
	/**					**					*/		updateDisplay:						function()							{	if(colors.color!='#NaNNaNNaN'){var angle=colors.hsl[0]*6.28;$('.h-marker',colors.e).css({left:Math.round(Math.sin(angle)*84+194/2)+'px',top:Math.round(-Math.cos(angle)*84+194/2)+'px'});$('.sl-marker',colors.e).css({left:Math.round(100*(.5-colors.hsl[1])+194/2)+'px',top:Math.round(100*(.5-colors.hsl[2])+194/2)+'px'});$('#colorBox .bottom .preview').css({background:colors.color});$('#colorBox .bottom .preview').css("color",colors.isDark($('#colorBox .bottom .preview').css("background-color"))?'white':'black');$('#colorBox .bottom .preview').html(colors.color);} },
	/**					**					*/		setHSL:								function(hsl) 						{	colors.hsl=hsl;colors.rgb=colors.HSLToRGB(hsl);colors.color=colors.pack(colors.rgb);colors.updateDisplay(); },
	/**					**					*/		isDark:								function(color)						{	var match=/rgb\((\d+).*?(\d+).*?(\d+)\)/.exec(color);return parseFloat(match[1])+parseFloat(match[2])+parseFloat(match[3])<3*256/2; },
	/**					**					*/		HSLToRGB:							function(hsl) 						{	var m1,m2,r,g,b,h=hsl[0],s=hsl[1],l=hsl[2];m2=(l<=0.5)?l*(s+1):l+s-l*s;m1=l*2-m2;return[colors.hueToRGB(m1,m2,h+0.33333),colors.hueToRGB(m1,m2,h),colors.hueToRGB(m1,m2,h-0.33333)]; },
	/**					**					*/		hueToRGB:							function(m1,m2,h)					{	h=(h<0)?h+1:((h>1)?h-1:h);if(h*6<1)return m1+(m2-m1)*h*6;if(h*2<1)return m2;if(h*3<2)return m1+(m2-m1)*(0.66666-h)*6;return m1; },
	/**					**					*/		pack:								function(rgb) 						{	var r=Math.round(rgb[0]*255),g=Math.round(rgb[1]*255),b=Math.round(rgb[2]*255);return '#'+(r<16?'0':'')+r.toString(16)+(g<16?'0':'')+g.toString(16)+(b<16?'0':'')+b.toString(16); },
	/**					**					*/	}
	/**					***************************************************************/
	/**					**	NOTIES			*/	var noty={
	/**					**					*/		type:								'',
	/**					**					*/		title:								'',
	/**					**					*/		content:							'',
	/**					**					*/		time:								0,
	/**					**					*/		statusDiv:							'',
	/**					**					*/		types:								[{type:'ambulance',img:'ambulance'},{type:'archive',img:'archive'},{type:'ban',img:'ban'},{type:'barcode',img:'barcode'},{type:'binoculars',img:'binoculars'},{type:'birthday',img:'birthday-cake'},{type:'bomb',img:'bomb'},{type:'bookmark',img:'bookmark-o'},{type:'calculator',img:'calculator'},{type:'calendar',img:'calendar'},{type:'camera',img:'camera-retro'},{type:'check',img:'check'},{type:'comment',img:'commenting-o'},{type:'cog',img:'cog'},{type:'cogs',img:'cogs'},{type:'desktop',img:'desktop'},{type:'download',img:'download'},{type:'edit',img:'pencil'},{type:'envelope',img:'envelope-o'},{type:'eraser',img:'eraser'},{type:'error',img:'times-circle'},{type:'exclamation',img:'exclamation-triangle'},{type:'fax',img:'fax'},{type:'floppy',img:'floppy-o'},{type:'folder',img:'folder'},{type:'globe',img:'globe'},{type:'home',img:'home'},{type:'info',img:'info'},{type:'key',img:'key'},{type:'keyboard',img:'keyboard-o'},{type:'lightbulb',img:'lightbulb-o'},
	/**					**					*/											{type:'laptop',img:'laptop'},{type:'lock',img:'lock'},{type:'magnet',img:'magnet'},{type:'map-marker',img:'map-marker'},{type:'minus',img:'minus-square-o'},{type:'music',img:'music'},{type:'newspaper',img:'newspaper-o'},{type:'paperclip',img:'paperclip'},{type:'plus',img:'plus-square-o'},{type:'percent',img:'percent'},{type:'picture',img:'picture-o'},{type:'pie-chart',img:'pie-chart'},{type:'plane',img:'plane'},{type:'plug',img:'plug'},{type:'phone',img:'phone'},{type:'print',img:'print'},{type:'question',img:'question'},{type:'refresh',img:'refresh'},{type:'recycle',img:'recycle'},{type:'scissor',img:'scissors'},{type:'shopping-basket',img:'shopping-basket'},{type:'shopping-cart',img:'shopping-cart'},{type:'sign-in',img:'sign-in'},{type:'sign-out',img:'sign-out'},{type:'sitemap',img:'sitemap'},{type:'sliders',img:'sliders'},{type:'sort-amount-asc',img:'sort-amount-asc'},{type:'sort-amount-desc',img:'sort-amount-desc'},{type:'star',img:'star'},{type:'tablet',img:'tablet'},
	/**					**					*/											{type:'television',img:'television'},{type:'trash',img:'trash-o'},{type:'unlock',img:'unlock'},{type:'upload',img:'upload'},{type:'user',img:'user'},{type:'user-plus',img:'user-plus'},{type:'users',img:'users'},{type:'warning',img:'bell-o'},{type:'wheelchair',img:'wheelchair'},{type:'wrench',img:'wrench'}],
	/**					**					*/		init:								function(opts)						{	noty.type=(opts.type?opts.type:'');noty.title=(opts.title?opts.title:'');noty.content=(opts.content?opts.content:'');noty.time=(opts.time?opts.time*1000:0);noty.show(); },
	/**					**					*/		show:								function()							{	if($('#noTy').length===0)var wrapper=$('<div id="noTy" class="noTy"></div>').addClass($.confs['noty-position']).appendTo('body');if($('.noTy-notifs').length>(parseInt($.confs['noty-max'])-1)){$('.noTy-notifs:first-child').stop().animate({height:'0px'},250,function(){$('.noTy-notifs:first-child').remove();});$('.noTy-notifs:eq(1)').addClass('first');}for(z=0;z<noty.types.length;z++){if(noty.types[z].type==noty.type)type=noty.types[z].img;}var notif_type=$('<div class="noty-symbol fa fa-'+type+'"></div>'),notif_close=$('<div class="noty-close"></div>'),notif_title=$('<div class="noty-title"></div>').html(noty.title),notif_content=$('<div class="noty-content"></div>').html(noty.content),notif_status=$('<div class="noty-status">'+(noty.time==0?'<i class="fa fa-thumb-tack"></i>':'')+'</div>');notif_type.append(notif_close);var notification=$('<div class="noTy-notifs"></div>').append(notif_type).append(notif_status).append(notif_title).append(notif_content).
	/**					**					*/																					append('<div class="clear"></div>');switch($.confs['noty-position']){case 'bottom-right':case 'bottom-left':if($('#noTy').find('.noTy-notifs:first-child').length){$('#noTy').find('.noTy-notifs:first-child').before(notification);}else{$('#noTy').append(notification);}break;case 'center':case 'top-left':case 'top-right':$('#noTy').append(notification);break;}notification.effect({effect:'fadeInLeft',delay:0,duration:500});notification.hover(function(){$(this).find('.noty-close').fadeIn('fast');},function(){$(this).find('.noty-close').fadeOut('fast');});notification.click(function(){$(this).stop().animate({height:'0px'},250,'swing',function(){$(this).remove();});});if(noty.time!=0){noty.status(notif_status);setTimeout(function(){notification.stop().animate({height:'0px'},250,'swing',function(){$(this).remove();});},noty.time);} },
	/**					**					*/		status:								function(el)						{	el.each(function(){var that=this;that.timerSeconds=noty.time/1000;that.timer=null;function stopWatch(){var seconds=(that.timerFinish-(new Date().getTime()))/1000;if(seconds<=0){clearInterval(that.timer);drawTimer(100);}else{var percent=100-((seconds/(that.timerSeconds))*100);drawTimer(percent);}}function start(){that.timerFinish=new Date().getTime()+(that.timerSeconds*1000);drawTimer(0);that.timer=setInterval(function(){stopWatch();},50);}function drawTimer(percent){$(that).html('<div class="slice'+(percent>50?' gt50"':'"')+'>'+'<div class="pie"></div>'+(percent>50?'<div class="pie fill"></div>':'')+'</div>');var deg=360/100*percent;$(that).find('.slice .pie').css({'-moz-transform':'rotate('+deg+'deg)','-webkit-transform':'rotate('+deg+'deg)','-o-transform':'rotate('+deg+'deg)','transform':'rotate('+deg+'deg)'});}$(this).addClass('pietimer fill');start();}); }
	/**					**					*/	}
	/**					***************************************************************/
	/**					**  FONTS			*/	var fonts={
	/**					**					*/		fonts:								['Arial','Arial Black','Book Antiqua','Comic Sans MS','Courier','Courier New','cursive','Gadget','Geneva','Georgia','Helvetica','Lucida Console','Lucida Grande','Lucida Sans Unicode','Monaco','monospace','MS Serif','New York','Palatino','sans-serif','serif','Tahoma','Times','Times New Roman','Trebuchet MS','Verdana'],
	/**					**					*/		init:								function(opts)						{	var layout='';for(z=0;z<fonts.fonts.length;z++){layout+='<div class="line">'+'<div class="sel '+(opts.font==fonts.fonts[z]?'selected':'')+' fa fa-circle'+(opts.font==fonts.fonts[z]?'':'-o')+'" fonts="'+fonts.fonts[z]+'"></div>'+'<div class="fnts" style="font-family:'+fonts.fonts[z]+'">'+fonts.fonts[z]+'</div>'+'</div>';}box.block('<div id="fonts">'+layout+'</div>');$('#fonts').find('.line').each(function(index,element){$(this).click(function(e){$('#fonts').find('.sel').each(function(index,element){$(this).removeClass('fa-circle fa-circle-o selected').addClass('fa-circle-o');});$(this).find('.sel').addClass('fa-circle selected');opts.callback($('#fonts').find('.selected').attr('fonts'));box.close();});}); }
	/**					**					*/	}
	/**					***************************************************************/	
	/** 				**  BOX				*/	var box={		
	/**					**					*/		content:							'',
	/**					**					*/		modal:								'',
	/**					**					*/		blocker:							'',
	/**					**					*/		closeButton:						'',		
	/**					**					*/		loading:							function(opts)						{	box._core('<ul class="loader">'+'<li></li>'+'<li></li>'+'<li></li>'+'<li></li>'+'<li></li>'+'</ul>'+'<div class="clear"></div>'+'<br/>'+'<div class="loading-text">'+opts.text+'</div>','loading');if(opts.time){setTimeout(function(){box.close();},opts.time*1000);} },
	/**					**					*/		block:								function(content)					{	box._core(content,'block');$('.box-block').elements(); },
	/**					**					*/		confirm:							function(content)					{	var buttons='',btt=content.buttons.split('|'),btt_yes='<button class="green">'+$.langs['confirm-yes']+'</button>',btt_ok='<button class="green">'+$.langs['confirm-ok']+'</button>',btt_cancel='<button class="dsgnmoo">'+$.langs['confirm-cancel']+'</button>',btt_no='<button class="dsgnmoo">'+$.langs['confirm-no']+'</button>';for(z=0;z<btt.length;z++){switch(btt[z]){case 'yes':buttons+=btt_yes;break;case 'ok':buttons+=btt_ok;break;case 'cancel':buttons+=btt_cancel;break;case 'no':buttons+=btt_no;}}box._core('<div class="confirm-title icon icon-question">'+($.langs[content.title]?$.langs[content.title]:content.title)+'</div>'+'<div class="confirm-text">'+($.langs[content.message]?$.langs[content.message]:content.message)+'</div>'+'<div class="confirm-divider"></div>'+'<div class="confirm-buttons">'+buttons+'</div>'+'<div class="clear"></div>','confirm');$('.box .green').click(function(){content.callback('1');$(this).unbind('click.confirm');
	/**					**					*/																					box.close();});$('.box .dsgnmoo').click(function(){content.callback('0');$(this).unbind('click.confirm');box.close();}); },
	/**					**					*/		resize:								function(x,y)						{	$('.box').css({'width':x,'height':y}); },		
	/**					**					*/		_core:								function(content,type)				{	box.content=content;box._cover();box._modal(type);box.closeButton.click(function(){box.close();return false;});if(type!='loading'){box.blocker.click(function(){box.close();});$(document).bind('keydown.modal',function(event){if(event.which==27)box.close();});} },
	/**					**					*/		_cover:								function(type)						{	box.blocker=$('<div class="blocker"></div>').css({top:0,right:0,bottom:0,left:0,width:"100%",height:"100%",position:"fixed",zIndex:100000,background:'#000000',opacity:0});$('body').append(box.blocker); },
	/**					**					*/		_modal:								function(mode)						{	box.modal=$('<div class="box box-'+mode+'" style="display:none;">'+'<div class="content '+mode+'">'+box.content+'</div>'+'</div>');$('body').append(box.modal);box.closeButton=$('<a href="#close-modal" rel="modal:close" class="fa fa-close close-modal"></a>').data('type','box');if(mode!='loading')box.modal.append(box.closeButton);box._centralize();box.blocker.animate({opacity:'.65'});box.modal.fadeIn(); },
	/**					**					*/		_centralize:						function()							{	box.modal.css({position:'fixed',top:"50%",left:"50%",marginTop:-(box.modal.outerHeight()/2),marginLeft:-(box.modal.outerWidth()/2),zIndex:100003}); },																
	/**					**					*/		close:								function()							{	box.modal.fadeOut(function(){$(this).remove();});box.blocker.fadeOut(function(){$(this).remove();});$(document).unbind('keydown.modal'); }
	/**					**					*/	}
	/****************************************/
	/****************************************/
	/** PAGINATION							*/	$.fn.pagination=function(options){
	/**										*/		return this.each(function(){
	/**										*/			var that=this;
	/**										*/			this.init=						function(options)					{	that.o=$.extend({items:1,perPage:1,pages:0,displayedPages:5,page:0,onClick:function(page,event){}},options||{});var self=this;that.o.pages=that.o.pages?that.o.pages:Math.ceil(that.o.items/that.o.perPage)?Math.ceil(that.o.items/that.o.perPage):1;if(that.o.page){that.o.page=that.o.page-1;}else{that.o.page=0;}that.o.halfDisplayed=that.o.displayedPages/2;$(that).addClass('paginationTheme pagination');that.draw(); }
	/**										*/			this.draw=						function() 							{	var	interval=that.getInterval(that.o),i,tagName;$(that).html('');tagName=$(that).attr('tagName');var $panel=$('<ul></ul>').appendTo($(that));that.appendItem(0,{text:'',classes:'prev fa fa-step-backward'});that.appendItem(that.o.page-1,{text:'',classes:'prev fa fa-caret-left'});if(interval.start>0){if(2<interval.start&&(interval.start-2!=1))$panel.append('<li class="disabled"><span class="paginationEllipse">&hellip;</span></li>');}for(i=interval.start;i<interval.end;i++){that.appendItem(i);}if(interval.end<that.o.pages){if(that.o.pages-2>interval.end&&(that.o.pages-2-interval.end!=1)){$panel.append('<li class="disabled"><span class="paginationEllipse">&hellip;</span></li>');}else if(that.o.pages-2-interval.end==1){that.appendItem(interval.end);}};that.appendItem(that.o.page+1,{text:'',classes:'fa fa-caret-right'});that.appendItem(that.o.pages,{text:'',classes:'fa fa-step-forward'}); };
	/**										*/			this.getInterval=				function(o) 						{	return{start:Math.ceil(that.o.page>that.o.halfDisplayed?Math.max(Math.min(that.o.page-that.o.halfDisplayed,(that.o.pages-that.o.displayedPages)),0):0),end:Math.ceil(that.o.page>that.o.halfDisplayed?Math.min(that.o.page+that.o.halfDisplayed,that.o.pages):Math.min(that.o.displayedPages,that.o.pages))}; };
	/**										*/			this.selectPage=				function(pageIndex,event) 			{	that.o.page=pageIndex;that.draw();return that.o.onClick(pageIndex+1,event); };
	/**										*/			this.appendItem=				function(pageIndex,opts) 			{	var options,$link,o=that.o,$linkWrapper=$('<li></li>'),$ul=$(that).find('ul');pageIndex=pageIndex<0?0:(pageIndex<o.pages?pageIndex:o.pages-1);options={text:pageIndex+1,classes:''};options=$.extend(options,opts||{});if(pageIndex==o.page||o.disabled){$linkWrapper.addClass('active');$link=$('<span class="current">'+(options.text)+'</span>');}else{$link=$('<a class="page-link">'+(options.text)+'</a>');$link.click(function(event){return that.selectPage(pageIndex,event);});}if(options.classes)$link.addClass(options.classes);$linkWrapper.append($link);if($ul.length){$ul.append($linkWrapper);}else{self.append($linkWrapper);} };
	/**										*/			this.init(options);
	/**										*/		});
	/**										*/	};			
	/****************************************/
	/** FN FUNCTIONS	**	EFFECTS			*/	$.fn.effect=function(opts){
	/**					**					*/		return this.each(function(){
	/**					**					*/			var that=this;
	/**					**					*/			that.allEffects=				['bounce','flash','rubberBand','shake','headShake','swing','tada','wobble','jello','pulse','bounceIn','bounceInDown','bounceInLeft','bounceInRight','bounceInUp','bounceOut','bounceOutDown','bounceOutLeft','bounceOutRight','bounceOutUp','fadeIn','fadeInDown','fadeInDownBig','fadeInLeft','fadeInLeftBig','fadeInRight','fadeInRightBig','fadeInUp','fadeInUpBig','fadeOut','fadeOutDown','fadeOutDownBig','fadeOutLeft','fadeOutLeftBig','fadeOutRight','fadeOutRightBig','fadeOutUp','fadeOutUpBig','flipInX','flipInY','flipOutX','flipOutY','lightSpeedIn','lightSpeedOut','rotateIn','rotateInDownLeft','rotateInDownRight','rotateInUpLeft','rotateInUpRight','rotateOut','rotateOutDownLeft','rotateOutDownRight','rotateOutUpLeft','rotateOutUpRight','hinge','rollIn','rollOut','zoomIn','zoomInDown','zoomInLeft','zoomInRight','zoomInUp','zoomOut','zoomOutDown','zoomOutLeft','zoomOutRight','zoomOutUp','slideInDown','slideInLeft','slideInRight','slideInUp','slideOutDown','slideOutLeft',
	/**					**					*/											'slideOutRight','slideOutUp'];
	/**					**					*/			this.init=						function(opts)						{	$(that).css({'-webkit-animation-duration':opts.duration+'ms','-moz-animation-duration':opts.duration+'ms','-ms-animation-duration':opts.duration+'ms','animation-duration':opts.duration+'ms','-webkit-animation-delay':opts.delay+'ms','-moz-animation-delay':opts.delay+'ms','-ms-animation-delay':opts.delay+'ms','animation-delay':opts.delay+'ms'});that.clear();$(that).addClass(opts.effect+' animated').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){that.clear();if(opts.callback)opts.callback('done');}); }
	/**					**					*/			this.clear=						function()							{	$(that).removeClass(that.allEffects.join(' ')); }
	/**					**					*/			this.init( opts);
	/**					**					*/		});
	/**					**					*/	}
	/****************************************/
	/****************************************/	
	/** ELEMENTS		**	INIT			*/	$.fn.elements=function(){
	/**					**					*/		return this.each(function(){
	/**					**					*/			var that=this;
	/**					**					*/			this.init=						function()							{	if($(that).hasClass('gallery'))that.gallery();if($(that).is('tab'))that.tabs();if($(that).is('select'))that.select();if($(that).is('textarea')&&$(that).hasClass('editor'))that.editor();if($(that).hasClass('accordion'))that.accordion();if($(that).is('input')){if($(this).attr('type')!='button')$(this).addClass('input_core');switch($(this).attr('type')){case 'color':that.color();break;case 'date':that.date();break;case 'font':that.font();break;case 'strength':that.strength();break;case 'time':that.time();break;case 'rate':that.rate();break;case 'numeric':case 'currency':that.numeric();break;};} }	
	/**					***************************************************************/
	/**					**  COLOR			*/			this.color=						function()							{	$(that).addClass('color');$(that).keydown(function(){return false;});if($(that).prop('value')!='')$(that).prop('value','#000000');$(that).addClass('color').attr('type','text');that.color_refresh();$(that).click(function(){colors.init({color:$(that).prop('value'),callback:function(e){$(that).prop('value',e);that.color_refresh();}});}); }
	/**					**					*/			this.color_refresh=				function()							{	$(that).css({'background':'#febf01','background':'-moz-linear-gradient(left,'+$(that).prop('value')+' 0%,'+$(that).prop('value')+',#ffffff 25%)','background':'-webkit-linear-gradient(left,'+$(that).prop('value')+' 0%,'+$(that).prop('value')+' 25%,#ffffff 25%)','background':'linear-gradient(to right,'+$(that).prop('value')+' 0%,'+$(that).prop('value')+' 25%,#ffffff 25%)','filter':'progid:DXImageTransform.Microsoft.gradient(startColorstr="'+$(that).prop('value')+'",endColorstr="#ffffff",GradientType=1)'}); }															
	/**					***************************************************************/
	/**					**	NUMERIC			*/			this.numeric=					function()							{	if($(that).prop('value')==''&&$(that).attr('type')=='currency')$(that).prop('value','0.00').addClass('currency');$(that).keydown(function(event){switch(event.keyCode){case 48:case 96:vChar='0';break;case 49:case 97:vChar='1';break;case 50:case 98:vChar='2';break;case 51:case 99:vChar='3';break;case 52:case 100:vChar='4';break;case 53:case 101:vChar='5';break;case 54:case 102:vChar='6';break;case 55:case 103:vChar='7';break;case 56:case 104:vChar='8';break;case 57:case 105:vChar='9';break;case 8:vChar='DEL';break;default:vChar='';}if(vChar!=''){switch($(that).attr('type')){case 'contact':case 'numeric':$(that).prop('value',(vChar!='DEL'?$(that).prop('value')+vChar:$(that).prop('value').
	/**					**	CURRENCY		*/																					substring(0,$(that).prop('value').length-1)));break;case 'currency':value=$(that).prop('value').replace(/,/g,'').replace('.','').replace(/ /g,'');(vChar!='DEL'?value+=vChar:value=value.substring(0,value.length-1));$(that).prop('value',that.numeric_formatNumber(parseInt(value)*0.01,2,'.',','));}}return false;}); }
	/**					**					*/			this.numeric_formatNumber=		function(val,c,d,t)					{	var c=isNaN(c=Math.abs(c))?2:c,d=d==undefined?".":d,t=t==undefined?",":t,s=val<0?"-":"",i=parseInt(val=Math.abs(+val||0).toFixed(c))+"",j=(j=i.length)>3?j%3:0;return s+(j?i.substr(0,j)+t:"")+i.substr(j).replace(/(\d{3})(?=\d)/g,"$1"+t)+(c?d+Math.abs(val-i).toFixed(c).slice(2):""); },
	/**					***************************************************************/
	/**					**	SELECT			*/			this.select=					function()							{	that.OP_csvDispCount=3;that.is_multi=$(that).attr('multiple');that.select='';that.caption='';that.placeholder='';that.optDiv='';that.CaptionCont='';that.ul='';that.is_opened=false;that.Pstate=[];that.select_createElems();that.select_setText(); }
	/**					**					*/			this.select_createLi=			function(opt,d) 					{	if(!opt.attr('value'))opt.attr('value',opt.val());li=$('<li class="opt"><label>'+opt.text()+'</label></li>');li.data('opt',opt);opt.data('li',li);if(that.is_multi)li.prepend('<span><i></i></span>');if(opt[0].disabled||d)li=li.addClass('disabled');that.select_onOptClick(li);if(opt[0].selected)li.addClass('selected');if(opt.attr('class'))li.addClass(opt.attr('class'));return li; }
	/**					**					*/			this.select_onOptClick=			function(li) 						{	li.click(function(){var li=$(this);if(li.hasClass('disabled'))return;txt="";if(that.is_multi){li.toggleClass('selected');li.data('opt')[0].selected=li.hasClass('selected');}else{that.ul.find('li').each(function(){$(this).removeClass('selected');});li.addClass('selected');li.data('opt')[0].selected=true;}that.select_setText();that.select_callChange();if(!that.is_multi)that.select_hideOpts();}); }
	/**					**					*/			this.select_basicEvents=		function() 							{	that.CaptionCont.click(function(evt){$(that).trigger('click');if(that.is_opened){that.select_hideOpts();}else{that.select_showOpts();}evt.stopPropagation();});that.select.on('keydown.selectBox',function(e){switch(e.which){case 38:that.nav(true);break;case 40:that.nav(false);break;case 13:if(that.is_opened)that.optDiv.find('ul li.sel').trigger('click');else that.setOnOpen();break;case 9:case 27:that.select_hideOpts();return;default:return;}e.preventDefault();});$(window).on('resize.selectBox',function(){that.optDiv.css('height','');}); }
	/**					**					*/			this.select_prepItems=			function(opts,d)					{	var lis=[];$(opts).each(function(i,opt){opt=$(this);lis.push(opt.is('optgroup')?$('<li class="group '+(opt[0].disabled?'disabled':'')+'"><label>'+opt.attr('label')+'</label><ul></ul><li>').find('ul').append(that.select_prepItems(opt.children(),opt[0].disabled)).end():that.select_createLi(opt,d));});return lis; }
	/**					**					*/			this.select_hideOpts=			function() 							{	if(that.is_opened){that.is_opened=false;that.optDiv.effect({effect:'zoomOut',delay:0,duration:300,callback:function(e){if(e=='done')that.select.removeClass('open').find('ul li.sel').removeClass('sel');}});$(document).off('click.selectBox');that.select.focus();$('body').removeClass('sumoStopScroll');} }
	/**					**					*/			this.select_callChange=			function()							{	$(that).trigger('change').trigger('click'); }
	/**					**					*/			this.select_getSelStr=			function() 							{	sopt=[];$(that).find('option:selected').each(function(){sopt.push($(this).val());});return sopt.join(','); }
	/**					**					*/			this.select_showOpts=			function() 							{	if($(that).attr('disabled'))return;that.is_opened=true;that.select.addClass('open');that.optDiv.effect({effect:'rollIn',delay:0,duration:300});if(that.ftxt){that.ftxt.focus()}else{that.select.focus()}$(document).on('click.selectBox',function(e){if(!that.select.is(e.target)&&that.select.has(e.target).length===0){if(!that.is_opened)return;that.select_hideOpts()}});that.optDiv.css({'top':'0px','width':'250px','position':'absolute'}); }
	/**					**					*/			this.select_setText=			function() 							{	that.placeholder="";if(that.is_multi){sels=$(that).find(':selected').not(':disabled');for(i=0;i<sels.length;i++){if(i+1>=that.OP_csvDispCount&&that.OP_csvDispCount){if(sels.length==$(that).find('option').length&&$.langs['select-all-selected']){that.placeholder=$.langs['select-all-selected'].replace(/\{0\}/g,sels.length)+',';}else{that.placeholder=$.langs['select-selected'].replace(/\{0\}/g,sels.length)+',';}break;}else that.placeholder+=$(sels[i]).text()+", ";}that.placeholder=that.placeholder.replace(/,([^,]*)$/,'$1');}else{that.placeholder=$(that).find(':selected').not(':disabled').text();}is_placeholder=false;if(!that.placeholder){is_placeholder=true;that.placeholder=$(that).attr('placeholder');if(!that.placeholder)that.placeholder=$(that).find('option:disabled:selected').text();}that.placeholder=that.placeholder?that.placeholder:$.langs['select-here'];that.caption.html(that.placeholder);that.CaptionCont.attr('title',that.placeholder);
	/**					**					*/																					csvField=that.select.find('input.HEMANT123');if(csvField.length)csvField.val(that.select_getSelStr());if(is_placeholder){that.caption.addClass('placeholder');}else{that.caption.removeClass('placeholder');}return that.placeholder; }
	/**					**					*/			this.select_createElems=		function() 							{	that.size=$(that).outerWidth();$(that).wrap('<div class="selBox" tabindex="0">');that.select=$(that).parent();that.caption=$('<span>');that.CaptionCont=$('<p class="selCont"><label><i></i></label></p>').addClass('SelectBox').attr('style',$(that).attr('style')).prepend(that.caption);that.select.append(that.CaptionCont);if($(that).attr('disabled'))that.select.addClass('disabled').removeAttr('tabindex');if($(that).attr('name'))that.select.addClass('sumo_'+$(that).attr('name'));$(that).addClass('selBoxHide').attr('tabindex','-1');that.optDiv=$('<div class="selOpWrap">');that.optDiv.css('height','');that.ul=$('<ul class="opts">');that.optDiv.append(that.ul);that.ul.append(that.select_prepItems($(that).children()));that.optDiv.addClass(that.is_multi?'multiple':'simple');that.select.append(that.optDiv);that.select_basicEvents(); }
	/**					***************************************************************/
	/**					**	RATE			*/			this.rate=						function()							{	$(that).hide();var randNumForm=Math.floor((Math.random()*999999)+1);$(that).data('form',randNumForm);that.value=($(that).val()?$(that).val():'0');that.themes={widget:$('<div class="input_rate '+randNumForm+'"></div>'),close:$('<a class="fa fa-ban remove"></a>')};that.rate_create();if($(that).attr('readonly')!='readonly'&&$(that).attr('disabled')!='disabled'){that.themes.widget.find('.star').on({mouseenter:function(){that.rate_mouseEnter($(this));},mouseleave:function(){that.rate_mouseLeave();},click:function(){that.rate_click($(this));return false;}});that.themes.close.on({click:function(){that.rate_close();}});} };
	/**					**					*/			this.rate_create=				function()							{	that.themes.widget.insertAfter($(that));if($(that).attr('readonly')!='readonly'&&$(that).attr('disabled')!='disabled'){that.themes.widget.append(that.themes.close);}for(z=0;z<5;z++){that.themes.widget.append('<a href="#" data-rate="'+(z+1)+'" title="'+(z+1)+'" class="fa '+($(that).attr('readonly')!='readonly'&&$(that).attr('disabled')!='disabled'?'':'readonly')+' star star'+(z+1)+' '+($(that).val()<(z+1)?'fa-star-o':'fa-star')+'"></a>');} };
	/**                 **                  */			this.rate_mouseEnter=			function(el)						{	el.prevAll('.star').removeClass('fa-star fa-star-o').addClass('fa-star');el.nextAll('.star').removeClass('fa-star fa-star-o').addClass('fa-star-o');el.removeClass('fa-star fa-star-o').addClass('fa-star'); };
	/**                 **                  */			this.rate_mouseLeave=			function()							{	that.themes.widget.find('.star').removeClass('fa-star fa-star-o').addClass('fa-star-o');that.rate_update(); };
	/**					**					*/			this.rate_click=				function(el)						{	that.value=el.data('rate');$(that).val(el.data('rate')); };
	/**					**					*/			this.rate_update=				function()							{	that.themes.widget.find('a[data-rate="'+that.value+'"]').removeClass('fa-star fa-star-o').addClass('fa-star').prevAll('.star').removeClass('fa-star fa-star-o').addClass('fa-star'); };
	/**					**					*/			this.rate_close=				function()							{	that.value=0;$(that).val('0');that.themes.widget.find('.star').removeClass('fa-star fa-star-o').addClass('fa-star-o'); };
	/**					***************************************************************/
	/**					**	STRENGTH		*/			this.strength=					function()							{	$(that).addClass('strength').attr('type','password').data('type','strength');that.strength_getStatus();$(that).on("keyup",function(event){that.strength_getStatus();}); };
	/**					**					*/			this.strength_getStatus=		function()							{	switch(that.strength_checkVal($(that).prop('value'))){case 0:statClass='strength_low';break;case 1:statClass='strength_low';break;case 2:statClass='strength_medium';break;case 3:statClass='strength_high';}$(that).data('level',that.strength_checkVal($(that).prop('value')));$(that).removeClass('strength_low strength_medium strength_high').addClass('_strength '+statClass); };
	/**					**					*/			this.strength_checkVal=			function(val)						{	var quality=0;if(val.length>=parseInt($.confs['password-strength-min-length']))quality+=1;jQuery.each({rule_1:[/([a-zA-Z])/,/([0-9])/],rule_2:[/([!,%,&,@,#,$,^,*,?,_,~])/],rule_3:[/(.*[!,%,&,@,#,$,^,*,?,_,~].*[!,%,&,@,#,$,^,*,?,_,~])/]},function(i,currentRuleArray){quality+=(function(){var returnValue=0;for(i=0;i<currentRuleArray.length;i++){if(val.match(currentRuleArray[i])){returnValue=1;}else{returnValue=0;}}return returnValue;})();});if(val.length<parseInt($.confs['password-strength-min-length']))return 0;if(quality<2){return 1;}else if(quality==2){return 2;}else{return 3;} }
	/**					***************************************************************/
	/**					**	TIME			*/			this.time=						function()							{	$(that).attr('type','text');that.input_on=false;that.event=null;that.td_id=$('.time-clock').length;$(that).prop({'readonly':true}).addClass('input_time');$('body').append('<div class="input_time_wrap time-n2" id="time-clock-'+that.td_id+'">'+'<div class="time-overlay"></div>'+'<div class="time-clock">'+'<div class="time-deg time-n">'+'<div class="time-select">'+'<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 35.4" enable-background="new 0 0 100 35.4" xml:space="preserve">'+'<g>'+'<path fill="none" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="M98.1,33C85.4,21.5,68.5,14.5,50,14.5S14.6,21.5,1.9,33"/>'+'<line fill="none" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" x1="1.9" y1="33" x2="1.9" y2="28.6"/>'+
	/**					**					*/																					'<line fill="none" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" x1="1.9" y1="33" x2="6.3" y2="33"/>'+'<line fill="none" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" x1="98.1" y1="33" x2="93.7" y2="33"/>'+'<line fill="none" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" x1="98.1" y1="33" x2="98.1" y2="28.6"/>'+'</g>'+'</svg>'+'</div>'+'</div>'+'<div class="time-pointers">'+'<div></div>'+'<div></div>'+'</div>'+'<div class="td-time">'+'<span class="on"></span>'+':'+'<span></span>'+'</div>'+'</div>'+'</div>');that.container=$('#time-clock-'+that.td_id);that.overlay=that.container.find('.time-overlay');that.c=that.container.find('.time-clock');that.c.find('svg').attr('style',"stroke:#1977CC");that.init_deg=-1;that.event_deg=0;that.wheel_deg=0;that.td_h=0;that.td_m=0;that.c.find('.td-time span').on('click',function(e){var o=$(this);
	/**					**					*/																					that.c.find('.td-time span').removeClass('on');o.addClass('on');var v=parseInt(o.attr('data-id'));if(o.index()==0){deg=Math.round((v*360/23))}else{deg=Math.round((v*360/59))};that.init_deg=-1;that.event_deg=deg;that.wheel_deg=deg;that.time_rotation(deg)});that.c.find('.time-deg').on('touchstart mousedown',function(e){that.time_define_deg();e.preventDefault();clearInterval(that.alert);that.c.find('.time-deg').removeClass('time-n');that.c.find('.time-select').removeClass('td-rubber');that.input_on=true;var offset=that.c.offset(),center={y:offset.top+that.c.height()/2,x:offset.left+that.c.width()/2},a,b,deg,tmp,rad2deg=180/Math.PI;that.c.removeClass('td-rubber');$(window).on('touchmove mousemove',function(e){if(that.input_on==true){move=e;a=center.y-(core.isMobile()?e.originalEvent.touches[0].pageY:move.pageY);b=center.x-(core.isMobile()?e.originalEvent.touches[0].pageX:move.pageX);deg=Math.atan2(a,b)*rad2deg;if(deg<0)deg=360+deg;if(that.init_deg==-1)that.init_deg=deg;
	/**					**					*/																					tmp=Math.floor((deg-that.init_deg)+that.event_deg);if(tmp<0){tmp=360+tmp}else if(tmp>360){tmp=tmp%360};that.time_rotation(tmp)}})});$(document).on('touchend mouseup',function(){if(that.input_on){that.input_on=false;that.c.find('.time-deg').addClass('time-n');that.c.find('.time-select').addClass('td-rubber')}});that.time_create();that.time_events(); }
	/**					**					*/			this.time_parseTime=			function(text) 						{	var time=text.match(/(\d?\d):?(\d?\d?)/),h=parseInt(time[1],10),m=parseInt(time[2],10)||0;if(h>24){time=text.match(/(\d)(\d?\d?)/);h=parseInt(time[1],10);m=parseInt(time[2],10)||0;}var d=new Date();d.setHours(h);d.setMinutes(m);return d; }
	/**					**					*/			this.time_create=				function(value)						{	var d=$(that).prop('value')?that.time_parseTime($(that).prop('value')):new Date();that.span_h=that.c.find('.td-time span:first');that.span_m=that.c.find('.td-time span:last');var h,m;if(!parseInt(that.span_h.text())){h=that.time_num(d.getHours());}else{h=that.time_num(that.span_h.text());};if(!parseInt(that.span_m.text())){m=that.time_num(d.getMinutes());}else{m=that.time_num(that.span_m.text());}that.span_h.attr('data-id',h).text(h);that.span_m.attr('data-id',m).text(m);that.event_deg=Math.round((h*360/23));that.c.find('.time-pointers div:first').css('transform','rotate('+Math.round((m*360/59))+'deg)');that.time_rotation(that.event_deg);that.wheel_deg=that.event_deg;that.init_deg=-1; }
	/**					**					*/			this.time_num=					function(n)							{	return n<10?'0'+n:n }
	/**					**					*/			this.time_define_deg=			function()							{	var o=that.c.find('.td-time span.on'),v=parseInt(o.attr('data-id'));if(o.index()==0){deg=Math.round((v*360/23));}else{deg=Math.round((v*360/59));}that.init_deg=-1;that.event_deg=deg;that.wheel_deg=deg; };
	/**					**					*/			this.time_rotation=				function(deg)						{	var t=that.c.find('.td-time span.on'),value=t.attr('data-id');if(!value)value=0;var h=Math.round((deg*23/360)),m=Math.round((deg*59/360));if(t.index()==0){t.attr('data-id',that.time_num(h));t.text(that.time_num(h));}else{t.attr('data-id',that.time_num(m)).text(that.time_num(m));};that.wheel_deg=deg;that.c.find('.time-deg').css('transform','rotate('+(deg)+'deg)');if(t.index()==0){var c=Math.round((h*360/12));that.c.find('.time-pointers div:last').css('transform','rotate('+(c)+'deg)');}else{that.c.find('.time-pointers div:first').css('transform','rotate('+(deg)+'deg)');};that.td_h=that.c.find('.td-time span:first').attr('data-id');that.td_m=that.c.find('.td-time span:last').attr('data-id');if(Math.round(that.td_h)>=12&&Math.round(that.td_h)<24){var h=Math.round(that.td_h)-12,a='pm',A='PM';}else{var h=Math.round(that.td_h),a='am',A='AM';};if(h==0)h=12;
	/**					**					*/																					var str='HH:mm'.replace(/\b(H)\b/g,Math.round(that.td_h)).replace(/\b(h)\b/g,Math.round(h)).replace(/\b(m)\b/g,Math.round(that.td_m)).replace(/\b(HH)\b/g,that.time_num(Math.round(that.td_h))).replace(/\b(hh)\b/g,that.time_num(Math.round(h))).replace(/\b(mm)\b/g,that.time_num(Math.round(that.td_m))).replace(/\b(a)\b/g,a).replace(/\b(A)\b/g,A);$(that).val(str); };
	/**					**					*/			this.time_events=				function()							{	$(that).focus(function(e){e.preventDefault();$(that).blur();});$(that).click(function(e){that.container.fadeIn('fast');that.c.css({'top':($(that).offset().top+($(that).outerHeight()-8)),'left':($(that).offset().left+($(that).outerWidth()/2))-(that.c.outerWidth()/2)});});that.overlay.click(function(){that.container.fadeOut('fast');});$(window).on('resize',function(){that.time_define_deg();that.c.css({'top':($(that).offset().top+($(that).outerHeight()-8)),'left':($(that).offset().left+($(that).outerWidth()/2))-(that.c.outerWidth()/2)});}); }
	/**					***************************************************************/
	/**					**	ACCORDION		*/			this.accordion=					function()							{	that.accordion_openSubmenu();that.accordion_submenuIndics();that.accordion_addClickEffect(); }
	/**					**					*/			this.accordion_addClickEffect=	function()							{	var ink,d,x,y;$(that).find("a").bind("click touchstart",function(e){$(".accordion_ink").remove();if($(this).children(".accordion_ink").length===0){$(this).prepend("<span class='accordion_ink'></span>");}ink=$(this).find(".accordion_ink");ink.removeClass("accordion_animate-ink");if(!ink.height()&&!ink.width()){d=Math.max($(this).outerWidth(),$(this).outerHeight());ink.css({height:d,width:d});}ink.css({top:(e.pageY-$(this).offset().top-ink.height()/2)+'px',left:(e.pageX-$(this).offset().left-ink.width()/2)+'px'}).addClass("accordion_animate-ink");}); }
	/**					**					*/			this.accordion_submenuIndics=	function() 							{	if($(that).find('.submenu').length>0)$(that).find('.submenu').siblings("a").append("<span class='submenu-indicator'>+</span>"); }
	/**					**					*/			this.accordion_openSubmenu=		function() 							{	$(that).children("ul").find("li").bind('click touchstart',function(e){e.stopPropagation();e.preventDefault();var $subMenus=$(this).children('.submenu'),$allSubMenus=$(this).find('.submenu');if($subMenus.length>0){if($subMenus.css("display")=="none"){$subMenus.slideDown(200).siblings("a").addClass('submenu-indicator-minus');$(this).siblings().find('.submenu').slideUp(200).end().find("a").removeClass('submenu-indicator-minus');return false;}else{$(this).find('.submenu').delay(0).slideUp(200);}if($allSubMenus.siblings("a").hasClass('submenu-indicator-minus'))$allSubMenus.siblings("a").removeClass('submenu-indicator-minus');}window.location.href=$(this).children("a").attr("href");}); }
	/**					***************************************************************/
	/**					**	FORMS			*/
	/**					***************************************************************/
	/**					**	GRIDS			*/
	/**					***************************************************************/
	/** 				**	DATE			*/			this.date=						function()							{	$(that).attr('type','text').hide();that.$newView=$('<input type="text" />');$(that).after(that.$newView);that.$newView.addClass('input_core').keydown(function(){return false;}).click(function(){$(that).trigger('click');});that.shortWeekDays=$.langs['date-short-week-days'].split(',');that.fullWeekDays=$.langs['date-full-week-days'].split(',');that.fullMonthNames=$.langs['date-full-month-names'].split(',');that.shortMonthNames=$.langs['date-short-month-names'].split(',');if($(that).prop('value')){that.$newView.prop('value',that.date_format(new Date($(that).prop('value')),$.confs['date_format']));that.$newView.attr({width: 'auto', size: that.$newView.prop('value').length-3});}$(that).click(function(e){that.date_getValue();box.block('<div id="dtPick">'+'<div class="navBox">'+'<div class="nav_prev_year fa fa-backward"></div>'+'<div class="nav_prev fa fa-caret-left"></div>'+'<div class="nav_home fa fa-home"></div>'+
	/**					**					*/																					'<div class="nav_clear fa fa-times"></div>'+'<div class="nav_month"></div>'+'<div class="nav_year"></div>'+'<div class="nav_next_year fa fa-forward"></div>'+'<div class="nav_next fa fa-caret-right"></div>'+'</div>'+'<div class="dateBox"></div>'+'</div>');that.date_dateFill();that.date_navEvents();that.date_dateEvents();}); };
	/**					**					*/			this.date_dateFill=				function()							{	$('.nav_prev_year').removeClass('disabled');$('.nav_next_year').removeClass('disabled');$('.nav_prev').removeClass('disabled');$('.nav_next').removeClass('disabled');$('.nav_home').removeClass('disabled');$('.nav_clear').removeClass('disabled');this.date_dateEventsOff();$('#dtPick .dateBox').unbind('mousewheel.dtPick');nBlock=0;dtBlock='';var numBlocks=0;for(z=0;z<7;z++){dtBlock+='<div class="dateHead">'+that.shortWeekDays[z]+'</div>';}lastMonthNDays=(that.date_getDaysMonth((that.currentDate.getMonth()==11?that.currentDate.getFullYear()-1:that.currentDate.getFullYear()),(that.currentDate.getMonth()==11?0:that.currentDate.getMonth()-1)))-(that.currentDateDayOne.getDay());for(z=0;z<(that.currentDateDayOne.getDay()+1);z++){dtBlock+='<div class="lastMonth dateBlockOff" data-day="'+lastMonthNDays+'">'+lastMonthNDays+'</div>';nBlock++;lastMonthNDays++;numBlocks++;}numDays=that.date_getDaysMonth(that.currentDate.getFullYear(),
	/**					**					*/																					that.currentDate.getMonth());for(z=0;z<numDays;z++){dtBlock+='<div class="dateBlockOn select'+(that.currentDate.getDate()==(z+1)?' selected':'')+'" data-day="'+(z+1)+'">'+(z+1)+'</div>';nBlock++;numBlocks++;}nextMonthNDays=1;fDays=0;if(nBlock<35){fDays=35-nBlock;}else if(nBlock<42){fDays=42-nBlock;}for(z=0;z<fDays;z++){dtBlock+='<div class="nextMonth dateBlockOff" data-day="'+nextMonthNDays+'">'+nextMonthNDays+'</div>';nextMonthNDays++;numBlocks++;}for(z=numBlocks;z<42;z++){dtBlock+='<div class="nextMonth dateBlockOff" data-day="'+nextMonthNDays+'">'+nextMonthNDays+'</div>';nextMonthNDays++;}$('#dtPick .dateBox').html(dtBlock);$('#dtPick .nav_year').html(that.currentDate.getFullYear());$('#dtPick .nav_month').html(that.fullMonthNames[that.currentDate.getMonth()]);that.date_dateEvents(); };
	/**					**					*/			this.date_navEvents=			function()							{	$('#dtPick .nav_prev_year').on('click',function(){if($(this).hasClass('disabled')==false){that.currentDate.setFullYear(that.currentDate.getFullYear()-1);that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()-1);that.date_dateFill();}});$('#dtPick .nav_next_year').on('click',function(){if($(this).hasClass('disabled')==false){that.currentDate.setFullYear(that.currentDate.getFullYear()+1);that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()+1);that.date_dateFill();}});$('#dtPick .nav_prev').on('click',function(){if($(this).hasClass('disabled')==false)that.date_prevNextMonth('prev');});$('#dtPick .nav_next').on('click',function(){if($(this).hasClass('disabled')==false)that.date_prevNextMonth('next');});$('#dtPick .nav_home').on('click',function(){if($(this).hasClass('disabled')==false)that.date_navHomeClick();}).on('dblclick',function(){if($(this).hasClass('disabled')==false)that.date_navHomeDblClick();});
	/**					**					*/																					$('#dtPick .nav_month').on('click',function(){that.date_monthsBox();});$('#dtPick .nav_year').on('click',function(){that.date_yearsBox();});$('#dtPick .nav_clear').on('click',function(){if($(this).hasClass('disabled')==false)that.date_clearValue();}); };
	/**					**					*/			this.date_navHomeClick=			function()							{	that.currentDate=new Date();that.currentDateDayOne=new Date();that.currentDateDayOne.setDate(1);that.date_dateFill(); };
	/**					**					*/			this.date_navHomeDblClick=		function()							{	that.date_setValue();box.close(); };
	/**					**					*/			this.date_dateEvents=			function()							{	$('#dtPick .dateBox .select').on('click.dtPick',function(){that.date_dateClick($(this));});$('#dtPick .lastMonth').on('click.dtPick',function(){that.date_dateOffDays($(this),'last');});$('#dtPick .nextMonth').on('click.dtPick',function(){that.date_dateOffDays($(this),'next');});$('#dtPick .dateBox').on('mousewheel.dtPick',function(e){that.date_prevNextMonth((e.originalEvent.wheelDelta>=0?'prev':'next'));}); };
	/**					**					*/			this.date_dateClick=			function(el)						{	that.currentDate.setDate(el.data('day'));that.date_dateFill();that.date_setValue();box.close(); };
	/**					**					*/			this.date_dateOffDays= 			function(el,or)						{	if(or=='last'){if(that.currentDate.getMonth()==0){that.currentDate.setFullYear(that.currentDate.getFullYear()-1);that.currentDate.setMonth(11,el.data('day'));that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()-1);that.currentDateDayOne.setMonth(11,1);}else{that.currentDate.setMonth((that.currentDate.getMonth()-1),el.data('day'));that.currentDateDayOne.setMonth(that.currentDate.getMonth(),1);}}else{if(that.currentDate.getMonth()==11){that.currentDate.setFullYear(that.currentDate.getFullYear()+1);that.currentDate.setMonth(0);that.currentDate.setDate(el.data('day'));that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()+1);that.currentDateDayOne.setMonth(0,1);}else{that.currentDate.setMonth(that.currentDate.getMonth()+1);that.currentDate.setDate(el.data('day'));that.currentDateDayOne.setMonth(that.currentDate.getMonth()+1,1);}}that.date_dateFill(); };
	/**					**					*/			this.date_dateEventsOff=		function()							{	$('#dtPick .dateBox .select').off('click.dtPick');$('#dtPick .lastMonth').off('click.dtPick');$('#dtPick .nextMonth').off('click.dtPick');$('#dtPick .dateBox').off('mousewheel.dtPick'); };
	/**					**					*/			this.date_monthsBox=			function()							{	$('.nav_prev_year').addClass('disabled');$('.nav_next_year').addClass('disabled');$('.nav_prev').addClass('disabled');$('.nav_next').addClass('disabled');$('.nav_home').addClass('disabled');$('.nav_clear').addClass('disabled');that.date_dateEventsOff();selMonth='';for(z=0;z<12;z++){selMonth+='<div class="monthSel'+(that.currentDate.getMonth()==z?' selected':' select')+'" data-month="'+z+'">'+that.fullMonthNames[z]+'</div>';}$('#dtPick .dateBox').html(selMonth);$('#dtPick .dateBox').find('.monthSel').click(function(){that.date_monthsBoxClick($(this));}); };
	/**					**					*/			this.date_monthsBoxClick=		function(el)						{	that.currentDate.setMonth(el.data('month'));that.currentDateDayOne.setMonth(el.data('month'),1);that.date_dateFill(); };
	/**					**					*/			this.date_yearsBox=				function()							{	$('.nav_prev_year').addClass('disabled');$('.nav_next_year').addClass('disabled');$('.nav_home').addClass('disabled');$('.nav_clear').addClass('disabled');that.date_dateEventsOff();that.yearsBoxNum=that.currentDate.getFullYear()-12;that.date_yearsBoxBuild();$('#dtPick .dateBox').on('mousewheel.dtPick',function(event){that.date_yearsBoxPrevNext((event.originalEvent.wheelDelta>=0?'prev':'next'));});$('#dtPick .nav_prev').on('click.dtPick',function(){that.date_yearsBoxPrevNext('prev');});$('#dtPick .nav_next').on('click.dtPick',function(){that.date_yearsBoxPrevNext('next');}); };
	/**					**					*/			this.date_yearsBoxBuild=		function()							{	selYear='';if(that.yearsBoxNum<$.confs['date_yearMin'])that.yearsBoxNum=parseInt($.confs['date_yearMin']);if(that.yearsBoxNum>parseInt($.confs['date_yearMax'])-24)that.yearsBoxNum=parseInt($.confs['date_yearMax'])-24;for(z=0;z<25;z++){selYear+='<div class="yearSel'+(that.currentDate.getFullYear()==(that.yearsBoxNum+z)?' selected':' select')+'" data-year="'+(that.yearsBoxNum+z)+'">'+(that.yearsBoxNum+z)+'</div>';}$('#dtPick .dateBox').html(selYear);$('#dtPick .dateBox').find('.yearSel').on('click.dtPick',function(){that.currentDate.setFullYear($(this).data('year'));that.currentDateDayOne.setFullYear($(this).data('year'));$('#dtPick .dateBox').off('mousewheel.dtPick');$('#dtPick .nav_prev').off('click.dtPick');$('#dtPick .nav_next').off('click.dtPick');that.date_dateFill();}); };
	/**					**					*/			this.date_yearsBoxPrevNext=		function(or)						{	if($('#dtPick .yearSel').length){if(or=='prev'){that.yearsBoxNum=that.yearsBoxNum-25;if(that.yearsBoxNum-24<$.confs['date_yearMin'])that.yearsBoxNum=parseInt($.confs['date_yearMin'])+20;}else if(or=='next'){that.yearsBoxNum=that.yearsBoxNum+25;if(that.yearsBoxNum+24>$.confs['date_yearMax'])that.yearsBoxNum=parseInt($.confs['date_yearMax'])-24;}that.date_yearsBoxBuild();} };
	/**					**					*/			this.date_prevNextMonth=		function(or)						{	if($('#dtPick .monthSel').length=='0'&&$('#dtPick .yearSel').length=='0'){if(or=='prev'){if(that.currentDate.getMonth()==0){that.currentDate.setFullYear(that.currentDate.getFullYear()-1);that.currentDate.setMonth(11);that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()-1);that.currentDateDayOne.setMonth(11,1);}else{that.currentDate.setMonth((that.currentDate.getMonth()-1),that.currentDate.getDate());that.currentDateDayOne.setMonth((that.currentDateDayOne.getMonth()-1),1);}}else{if(that.currentDate.getMonth()==11){that.currentDate.setFullYear(that.currentDate.getFullYear()+1);that.currentDate.setMonth(0);that.currentDateDayOne.setFullYear(that.currentDateDayOne.getFullYear()+1);that.currentDateDayOne.setMonth(0,1);}else{that.currentDate.setMonth((that.currentDate.getMonth()+1),that.currentDate.getDate());that.currentDateDayOne.setMonth((that.currentDateDayOne.getMonth()+1),1);}}that.date_dateFill();} };
	/**					**					*/			this.date_clearValue=			function()							{	that.date_navHomeClick();$(that).prop('value','');$(that).data('date',''); };
	/**					**					*/			this.date_getValue=				function()							{	that.currentDate=($(that).prop('value')?new Date($(that).prop('value')):new Date());that.currentDateDayOne=($(that).prop('value')?new Date($(that).prop('value')):new Date());that.currentDateDayOne.setDate(1);that.date_setValue(); };
	/**					**					*/			this.date_setValue=				function()							{	cDate=that.currentDate;pStr=cDate.getFullYear()+'-'+((cDate.getMonth()+1)<10?'0':'')+(cDate.getMonth()+1)+'-'+(cDate.getDate()<10?'0':'')+cDate.getDate();$(that).prop('value',pStr);that.$newView.prop('value',that.date_format(new Date(pStr),$.confs['date_format']));that.$newView.attr({width:'auto',size:that.$newView.prop('value').length-3}); };
	/**					**					*/			this.date_format=				function(date,format)				{	var pad=function(n,width,z){z=z||'0';n=n+'';return n.length>=width?n:new Array(width-n.length+1).join(z)+n;};var formats={'%a':function(){return that.shortWeekDays[date.getDay()];},'%b':function(){return that.shortMonthNames[date.getMonth()];},'%c':function(){return date.getMonth()+1;},'%d':function(){return pad(date.getDate(),2);},'%e':function(){return date.getDate();},'%M':function(){return that.fullMonthNames[date.getMonth()];},'%m':function(){return pad(this["%c"](),2);},'%W':function(){return that.fullWeekDays[date.getDay()];},'%Y':function(){return date.getFullYear();},'%y':function(){return(date.getFullYear()).toString().substring(2);}};var replacer=function(match){if(formats[match]==null)return match.substr(1,1);return formats[match]();};return format.replace(/\%.?/g,replacer); };
	/**					**					*/			this.date_getDaysMonth=			function(y,m)						{	return new Date(y,m+1,0).getDate(); }
	/**					***************************************************************/
	/**					**	FONT			*/			this.font=						function()							{	$(that).addClass('input_fonts');$(that).keydown(function(){return false;});$(that).click(function(){fonts.init({font:$(that).prop('value'),callback:function(e){$(that).prop('value',e);}});}); }
	/**					***************************************************************/
	/** 				**  EDITOR			*/			this.editor=					function()							{	that.buttons=[{name:'bold',title:$.langs['elements-editor-bold'],command:'bold',popupName:'',class:'fa fa-bold'},{name:'italic',title:$.langs['elements-editor-italic'],command:'italic',popupName:'',class:'fa fa-italic'},{name:'underline',title:$.langs['elements-editor-underline'],command:'underline',popupName:'',class:'fa fa-underline'},{name:'strikethrough',title:$.langs['elements-editor-strikethrough'],command:'strikethrough',popupName:'',class:'fa fa-strikethrough'},{name:'subscript',title:$.langs['elements-editor-subscript'],command:'subscript',popupName:'',class:'fa fa-subscript'},{name:'superscript',title:$.langs['elements-editor-superscript'],command:'superscript',popupName:'',class:'fa fa-superscript'},{name:'sep'},{name:'font',title:$.langs['elements-editor-font'],command:'fontname',popupName:'',class:'fa fa-font'},{name:'size',title:$.langs['elements-editor-size'],command:'fontsize',popupName:'size',class:'fa fa-text-width'},
	/**					**					*/																					{name:'style',title:$.langs['elements-editor-style'],command:'formatblock',popupName:'style',class:'fa fa-header'},{name:'sep'},{name:'color',title:$.langs['elements-editor-color'],command:'forecolor',popupName:'',class:'fa fa-pencil'},{name:'highlight',title:$.langs['elements-editor-highlight'],command:'hilitecolor',popupName:'',class:'fa fa-pencil-square-o'},{name:'removeformat',title:$.langs['elements-editor-removeformat'],command:'removeformat',popupName:'',class:'fa fa-leaf'},{name:'sep'},{name:'bullets',title:$.langs['elements-editor-bullets'],command:'insertunorderedlist',popupName:'',class:'fa fa-list'},{name:'numbering',title:$.langs['elements-editor-numbering'],command:'insertorderedlist',popupName:'',class:'fa fa-list-ol'},{name:'sep'},{name:'outdent',title:$.langs['elements-editor-outdent'],command:'outdent',popupName:'',class:'fa fa-outdent'},{name:'indent',title:$.langs['elements-editor-indent'],command:'indent',popupName:'',class:'fa fa-indent'},
	/**					**					*/																					{name:'sep'},{name:'alignleft',title:$.langs['elements-editor-alignleft'],command:'justifyleft',popupName:'',class:'fa fa-align-left'},{name:'center',title:$.langs['elements-editor-center'],command:'justifycenter',popupName:'',class:'fa fa-align-center'},{name:'alignright',title:$.langs['elements-editor-alignright'],command:'justifyright',popupName:'',class:'fa fa-align-right'},{name:'justify',title:$.langs['elements-editor-justify'],command:'justifyfull',popupName:'',class:'fa fa-align-justify'},{name:'sep'},{name:'undo',title:$.langs['elements-editor-undo'],command:'undo',popupName:'',class:'fa fa-undo'},{name:'redo',title:$.langs['elements-editor-redo'],command:'redo',popupName:'',class:'fa fa-repeat'},{name:'sep'},{name:'rule',title:$.langs['elements-editor-rule'],command:'inserthorizontalrule',popupName:'',class:'fa fa-i-cursor'},{name:'sep'},{name:'print',title:$.langs['elements-editor-print'],command:'print',popupName:'',class:'fa fa-print'}];that.styles=
	/**					**					*/																					[["Paragraph","<p>"],["Header 1","<h1>"],["Header 2","<h2>"],["Header 3","<h3>"],["Header 4","<h4>"],["Header 5","<h5>"],["Header 6","<h6>"]];that.sizes="1,2,3,4,5,6,7";var randNumForm=Math.floor((Math.random()*999999)+1);that.randNum=Math.floor((Math.random()*999999)+1);$(that).data('sub',that.randNum).data('form',randNumForm);that.ua=navigator.userAgent.toLowerCase();that.ie=/msie/.test(that.ua);that.iege11=/(trident)(?:.*rv:([\w.]+))?/.test(that.ua);that.popups={};that.documentClickAssigned;that.iOS=/iPhone|iPad|iPod/i.test(that.ua);that.ie6=/msie\s6/.test(that.ua);that.webkit=/webkit/.test(that.ua);that.useCSS=true;var $area=that.$area=$(that).css({border:"none",margin:0,padding:0}).hide().data("cleditor",that).blur(function(){that.editor_updateFrame(true);}),$main=that.$main=$("<div>").addClass("editorCore").addClass('sub_'+that.randNum+' '+randNumForm),$toolbar=that.$toolbar=$("<div>").addClass("editorCoreToolbar").appendTo($main),$group=$("<div>").addClass
	/**					**					*/																					("editorCoreGroup").appendTo($toolbar),groupWidth=0;$.each(that.buttons,function(idx){if(that.buttons[idx].name==="sep"){var $div=$("<div>").addClass("editorCoreDivider").appendTo($group);$group.width(groupWidth+1);groupWidth=0;$group=$("<div>").addClass("editorCoreGroup").appendTo($toolbar);}else if(that.buttons[idx].command=='fontsize'||that.buttons[idx].command=='formatblock'){var button=that.buttons[idx],$buttonDiv=$("<div>").data("buttonName",button.name).data("command",button.command).data("popupName",button.popupName).addClass("editorCoreButton").attr("title",button.title).bind("click",$.proxy(that.editor_buttonClick,that)).appendTo($group).hover(that.editor_hoverEnter,that.editor_hoverLeave);groupWidth+=24;$group.width(groupWidth+1);$buttonDiv.addClass(button.class);if(that.ie)$buttonDiv.attr("unselectable","on");if(button.popupName)that.editor_createPopup(button.popupName,button.popupClass,button.popupContent,button.popupHover);}else{var button=that.buttons
	/**					**					*/																					[idx],$buttonDiv=$("<div>").data("buttonName",button.name).data("command",button.command).data("popupName",button.popupName).addClass("editorCoreButton").attr("title",button.title).click(function(e){switch(button.command){case 'bold':case 'italic':case 'underline':case 'strikethrough':case 'subscript':case 'removeformat':case 'insertunorderedlist':case 'insertorderedlist':case 'outdent':case 'indent':case 'justifyleft':case 'justifycenter':case 'justifyright':case 'justifyfull':case 'undo':case 'redo':case 'inserthorizontalrule':case 'print':case 'superscript':that.editor_execCommand(button.command,e,that.useCSS,$buttonDiv);break;case 'fontname':fonts.init({font:'',callback:function(e){that.editor_execCommand(button.command,e,that.useCSS,$buttonDiv);}});break;case 'forecolor':case 'hilitecolor':colors.init({color:'#000',callback:function(e){that.editor_execCommand(button.command,e,that.useCSS,$buttonDiv);}});break;}}).appendTo($group).hover(that.editor_hoverEnter,
	/**					**					*/																					that.editor_hoverLeave);groupWidth+=24;$group.width(groupWidth+1);$buttonDiv.addClass(button.class);if(that.ie)$buttonDiv.attr("unselectable","on");if(button.popupName)that.editor_createPopup(button.popupName,button.popupClass,button.popupContent,button.popupHover);}});$main.insertBefore($area).append($area);if(!that.documentClickAssigned){$(document).click(function(e){var $target=$(e.target);if(!$target.add($target.parents()).is(".editorCorePrompt"))that.editor_hidePopups();});that.documentClickAssigned=true;}$(window).bind("resize.cleditor",function(){that.editor_refresh();});that.editor_refresh(); }
	/**					**					*/			this.editor_buttonClick=		function(e)							{	var buttonDiv=e.target,buttonName=$.data(buttonDiv,"buttonName"),button=$(e.target).data('buttonName'),popupName=$(e.target).data('popupName'),popup=that.popups[popupName];if(that.disabled||$(buttonDiv).attr("disabled")==="disabled")return;var data={that:that,button:buttonDiv,buttonName:buttonName,popup:popup,popupName:$(e.target).data('popupName'),command:$(e.target).data('command'),useCSS:that.useCSS};if(button.buttonClick&&button.buttonClick(e,data)===false)return false;if(!that.editor_sourceMode()){if(popupName){var $popup=$(popup);if(popupName==="pastetext"){$popup.children(":button").unbind("click").bind("click",function(){var $textarea=$popup.find("textarea"),text=$textarea.val().replace(/\n/g,"<br />");if(text!=="")that.editor_execCommand(data.command,text,null,data.button);$textarea.val("");that.editor_hidePopups();that.editor_focus()})}if(buttonDiv!==$.data(popup,"button")){that.editor_showPopup(popup,buttonDiv);
	/**					**					*/																					return false}return}else if(buttonName==="print"){that.$frame[0].contentWindow.print();}else if(!that.editor_execCommand(data.command,data.value,data.useCSS,buttonDiv)){return false}}that.editor_focus(); }
	/**					**					*/			this.editor_hoverEnter=			function(e)							{	var $div=$(e.target).closest("div");$div.css("backgroundColor",$div.data("buttonName")?"#FFF":"#FFC"); }
	/**					**					*/			this.editor_hoverLeave=			function(e)							{	$(e.target).closest("div").css("backgroundColor","transparent"); }
	/**					**					*/			this.editor_createPopup=		function(pNm,pTCl,pCon,pHv)			{	if(that.popups[pNm])return that.popups[pNm];var $popup=$("<div>").hide().addClass("editorCorePopup").appendTo("body");if(pCon){$popup.html(pCon);}else if(pNm==="size"){$.each(that.sizes.split(","),function(idx,size){$("<div>").appendTo($popup).html('<font size="'+size+'">'+size+'</font>')});}else if(pNm==="style"){$.each(that.styles,function(idx,style){$("<div>").appendTo($popup).html(style[1]+style[0]+style[1].replace("<","</"))});}if(!pTCl&&!pCon)pTCl="editorCoreList";$popup.addClass(pTCl);if(that.ie)$popup.attr("unselectable","on").find("div,font,p,h1,h2,h3,h4,h5,h6").attr("unselectable","on");if($popup.hasClass("editorCoreList")||pHv===true)$popup.children().hover(that.editor_hoverEnter,that.editor_hoverLeave);that.popups[pNm]=$popup[0];return $popup[0]; }
	/**					**					*/			this.editor_refresh=			function()							{	var $main=that.$main;if(that.$frame)that.$frame.remove();var $frame=that.$frame=$('<iframe frameborder="0" src="javascript:true;" />').hide().appendTo($main);var contentWindow=$frame[0].contentWindow,doc=that.doc=contentWindow.document,$doc=$(doc);if(that.ie||that.iege11)$doc.click(function(){that.editor_focus()});that.editor_updateFrame();if(that.ie||that.iege11){$doc.bind("beforedeactivate beforeactivate selectionchange keypress keyup",function(e){if(e.type==="beforedeactivate")that.inactive=true;else if(e.type==="beforeactivate"){if(!that.inactive&&that.range&&that.range.length>1)that.range.shift();delete that.inactive}else if(!that.inactive){if(!that.range)that.range=[];that.range.unshift(that.editor_getRange());while(that.range.length>2)that.range.pop()}});$frame.focus(function(){that.editor_restoreRange();});}else{}$doc.click(that.editor_hidePopups).keydown(function(e){if(that.ie&&that.editor_getSelection().type=="Control"&&e.keyCode==8)
	/**					**					*/																					{that.editor_getSelection().clear();e.preventDefault()}}).bind("keyup mouseup",function(){that.editor_refreshButtons();that.editor_updateTextArea(true)});if(that.iOS){that.$area.show();}else{$frame.show();$(function(){var $toolbar=that.$toolbar,$group=$toolbar.children("div:last"),wid=$main.width();var hgt=$group.offset().top+$group.outerHeight()-$toolbar.offset().top+1;$toolbar.height(hgt);hgt=$main.height()-70;$frame.width(wid).height(hgt);that.$area.width(wid).height(that.ie6?hgt-2:hgt);that.editor_disable(that.disabled);that.editor_refreshButtons()});} }
	/**					**					*/			this.editor_updateFrame=		function(checkForChange)			{	var code=that.$area.val(),updateFrameCallback=that.upFrame,$body=$(that.doc.body);if(updateFrameCallback){var sum=that.editor_checksum(code);if(checkForChange&&that.areaChecksum===sum)return;that.areaChecksum=sum}var html=updateFrameCallback?updateFrameCallback(code):code;html=html.replace(/<(?=\/?script)/ig,"&lt;");if(that.upTextArea)that.frameChecksum=that.editor_checksum(html);if(html!==$body.html())$body.html(html); }
	/**					**					*/			this.editor_hidePopups=			function()							{	$.each(that.popups,function(idx,popup){$(popup).hide().unbind("click").removeData("button");}); }
	/**					**					*/			this.editor_disable=			function(disabled)					{	if(disabled){that.$area.attr("disabled","disabled");that.disabled=true}else{that.$area.removeAttr("disabled");delete that.disabled}try{if(that.ie){that.doc.body.contentEditable=!disabled;}else{that.doc.designMode=!disabled?"on":"off"}}catch(err){}that.editor_refreshButtons(); }
	/**					**					*/			this.editor_refreshButtons=		function()							{	if(!that.iOS&&that.webkit&&!that.focused){that.$frame[0].contentWindow.focus();window.focus();that.focused=true}var queryObj=that.doc;if(that.ie)queryObj=that.editor_getRange();var inSourceMode=that.editor_sourceMode();$.each(that.$toolbar.find(".editorCoreButton"),function(idx,elem){var $elem=$(elem),button=$(elem).data('buttonName'),command=$(elem).data('command'),enabled=true;if(that.disabled){enabled=false;}else if(button.getEnabled){var data={that:that,button:elem,buttonName:button.name,popup:that.popups[button.popupName],popupName:button.popupName,command:button.command,useCSS:that.useCSS};enabled=button.getEnabled(data);if(enabled===undefined)enabled=true}else if(((inSourceMode||that.iOS))||(that.ie&&(command==="undo"||command==="redo"))){enabled=false;}else if(command&&command!=="print"){if(that.ie&&command==="hilitecolor")command="backcolor";if((!that.ie&&!that.iege11)||command!=="inserthtml"){try{enabled=
	/**					**					*/																					queryObj.queryCommandEnabled(command)}catch(err){enabled=false}}}if(enabled){$elem.removeClass("editorCoreOff");$elem.removeAttr("disabled")}else{$elem.addClass("editorCoreOff");$elem.attr("disabled","disabled")}}); }
	/**					**					*/			this.editor_sourceMode=			function()							{	return that.$area.is(":visible"); }
	/**					**					*/			this.editor_updateTextArea=		function(checkForChange)			{	var html=$(that.doc.body).html(),updateTextAreaCallback=that.upTextArea,$area=that.$area;if(updateTextAreaCallback){var sum=that.editor_checksum(html);if(checkForChange&&that.frameChecksum===sum)return;that.frameChecksum=sum}var code=updateTextAreaCallback?updateTextAreaCallback(html):html;if(that.upFrame)that.areaChecksum=that.editor_checksum(code);if(code!==$area.val()){$area.val(code);} }
	/**					**					*/			this.editor_execCommand=		function(comm,value,useCSS)			{	that.editor_restoreRange();if(!that.ie){if(useCSS===undefined||useCSS===null)useCSS=that.useCSS;that.doc.execCommand("styleWithCSS",0,useCSS.toString())}var success=true,message;try{success=that.doc.execCommand(comm,0,value||null)}catch(err){message=err.message;success=false}that.editor_refreshButtons();that.editor_updateTextArea(true);return success; }
	/**					**					*/			this.editor_showPopup=			function(popup,button)				{	var offset,left,top,$popup=$(popup);if(button){var $button=$(button);offset=$button.offset();left=--offset.left;top=offset.top+$button.height()}else{var $toolbar=that.$toolbar;offset=$toolbar.offset();left=Math.floor(($toolbar.width()-$popup.width())/2)+offset.left;top=offset.top+$toolbar.height()-2}that.editor_hidePopups();$popup.css({left:left,top:top}).show();if(button)$.data(popup,"button",button);$popup.bind("click",{popup:popup},$.proxy(that.editor_popupClick,that));setTimeout(function(){$popup.find(":text,textarea").eq(0).focus().select()},100); }
	/**					**					*/			this.editor_popupClick=			function(e)							{	var popup=e.data.popup,target=e.target;if(popup===that.popups.msg||$(popup).hasClass("editorCorePrompt"))return;var buttonDiv=$.data(popup,"button"),buttonName=$.data(buttonDiv,"buttonName"),button=that.buttons.filter(function(a){return a.name==buttonName})[0],command=button.command,value,useCSS=that.useCSS;if(buttonName==="font"){value=target.style.fontFamily.replace(/"/g,"");}else if(buttonName==="size"){if(target.tagName.toUpperCase()==="DIV")target=target.children[0];value=target.innerHTML}else if(buttonName==="style"){value="<"+target.tagName+">";}else if(buttonName==="color"){value=that.editor_hex(target.style.backgroundColor);}else if(buttonName==="highlight"){value=that.editor_hex(target.style.backgroundColor);if(that.ie){command='backcolor';}else{useCSS=true}}var data={that:that,button:buttonDiv,buttonName:buttonName,popup:popup,popupName:button.popupName,command:command,value:value,useCSS:useCSS};if(button.popupClick&&button.
	/**					**					*/																					popupClick(e,data)===false)return;if(data.command&&!that.editor_execCommand(data.command,data.value,data.useCSS,buttonDiv))return false;that.editor_hidePopups();that.editor_focus(); }
	/**					**					*/			this.editor_restoreRange=		function()							{	if(that.range){if(ie){that.range[0].select();}else if(that.iege11){that.editor_getSelection().addRange(that.range[0])}} }
	/**					**					*/			this.editor_hex=				function(s)							{	var m=/rgba?\((\d+), (\d+), (\d+)/.exec(s);if(m){s=(m[1]<<16|m[2]<<8|m[3]).toString(16);while(s.length<6)s="0"+s;return"#"+s}var c=s.split("");if(s.length===4)return"#"+c[1]+c[1]+c[2]+c[2]+c[3]+c[3];return s; }	
	/**					**					*/			this.editor_getSelection=		function()							{	if(ie)return that.doc.selection;return that.$frame[0].contentWindow.getSelection(); }
	/**					**					*/			this.editor_getRange=			function()							{	if(ie)return that.editor_getSelection().createRange();return that.editor_getSelection().getRangeAt(0); }
	/**					**					*/			this.editor_checksum=			function(text)						{	var a=1,b=0;for(var index=0;index<text.length;++index){a=(a+text.charCodeAt(index))%65521;b=(b+a)%65521}return(b<<16)|a; }	
	/**					**					*/			this.editor_focus=				function()							{	setTimeout(function(){if(that.editor_sourceMode()){that.$area.focus();}else{that.$frame[0].contentWindow.focus();}that.editor_refreshButtons()},0); }
	/**					***************************************************************/
	/**					**	TABS			*/			this.tabs=						function()							{	that.tabs_create();window.onresize=function(){$('body').find('.tabsHV').remove();$('body').find('tab').show().each(function(){$(this).elements();});}; }
	/**					**					*/			this.tabs_create=				function()							{	that.side=$(that).attr('side');that.$container=$('<div class="tabsHV '+($(that).attr('side')=='left'||$(that).attr('side')=='right'?'tabsHV-vert':'')+'"></div>');that.$nav=$('<nav></nav>');that.$navUl=$('<ul class="tabsHV-nav"></ul>');that.$content=$('<ul class="tabsHV-cont"></ul>');var contHeight=0,hHt=0,wHt=0,ttHeight=0;$(that).find('line').each(function(index){if(contHeight<$(this).height())contHeight=$(this).height();that.$navUl.append('<li><a '+($(this).attr('selected')||!$(that).find('line[selected]').length&&index==0?'class="selected"':'')+'>'+($(this).attr('icon')?'<i class="'+$(this).attr('icon')+'"></i>':'')+$(this).attr('label')+'</a></li>');that.$content.append('<li '+($(this).attr('selected')||!$(that).find('line[selected]').length&&index==0?'class="selected"':'')+'><p>'+$(this).html()+'</p></li>'+'<div class="clear"></div>')});that.$nav.append(that.$navUl);if(that.side=='bottom'){that.$container.append(that.$content);
	/**					**					*/																					that.$container.append(that.$nav)}else{that.$container.append(that.$nav);that.$container.append(that.$content)}that.$content.after('<div class="clear"></div>');$(that).after('<div class="clear"></div>');$(that).after(that.$container).hide();var total=0;that.$navUl.find('li').each(function(){total+=$(this).outerWidth();if(wHt<$(this).width())wHt=$(this).width();$(this).find('i').after('<div class="clear"></div>')});that.$nav.addClass(that.side);if($(that).attr('side')=='left'||$(that).attr('side')=='right'){that.$nav.css({'width':wHt});that.$navUl.css('width',wHt);that.$content.css({'width':'calc(100% - '+wHt+'px)','height':(that.$nav.innerHeight()<contHeight?contHeight:that.$nav.innerHeight())+'px'});that.$nav.css('height',(that.$nav.innerHeight()<contHeight?contHeight:that.$nav.innerHeight())+'px');that.$navUl.find('li').css('width',wHt)}else{that.$container.css('min-width',total+'px');that.$content.height(contHeight+'px')}that.$navUl.find('a').each(function(index)
	/**					**					*/																					{$(this).click(function(e){e.preventDefault();that.$navUl.find('a.selected').removeClass('selected');$(this).addClass('selected');that.$content.find('li').each(function(index2){$(this).removeClass('selected');if(index==index2)$(this).addClass('selected')})})}); }
	/**					***************************************************************/
	/**					** 	GALLERY			*/			this.gallery=					function()							{	$(that).addClass('gallery-hover');that.options={zIndex:2015};that.isBuilt=false;that.tooltiping=false;that.index=0;that.$images=$(that).find('img');that.length=that.$images.length;that.count=0;that.$body=$('body');$(that).find('img').each(function(index){$(this).attr('index',index);$(this).click(function(){that.index=Number($(this).attr('index'));that.gallery_show();});}); }
	/**					**					*/			that.gallery_show=				function() 							{	if(!that.isBuilt){that.gallery_build();}else{that.$viewer.css({'display':'block'});}that.$body.addClass('gallery-open');that.$viewer.removeClass('gallery-hide');that.$viewer.addClass('gallery-transition');that.$viewer.addClass('gallery-in');that.gallery_view(that.index); }
	/**					**					*/			this.gallery_build=				function()							{	that.$parent=$(that).parent();that.$viewer=$('<div class="gallery-container">'+'<div class="gallery-canvas"></div>'+'<div class="gallery-footer">'+'<div class="gallery-title"></div>'+'<ul class="gallery-toolbar">'+'<li class="galleryZoomInOut fa fa-plus"></li>'+'<li class="galleryZoomInOut fa fa-minus"></li>'+'<li class="viewer-reset fa fa-refresh"></li>'+'<li class="viewer-print fa fa-print"></li>'+'<li class="galleryPrevNext fa fa-chevron-left"></li>'+'<li class="galleryPrevNext fa fa-chevron-right"></li>'+'<li class="galleryRotateLeftRight fa fa-undo"></li>'+'<li class="galleryRotateLeftRight fa fa-repeat"></li>'+'<li class="galleryFlip fa fa-arrows-h"></li>'+'<li class="galleryFlip fa fa-arrows-v"></li>'+'</ul>'+'<div class="gallery-navbar">'+'<ul class="gallery-list"></ul>'+'</div>'+'</div>'+'<div class="gallery-tooltip"></div>'+'<div class="gallery-button fa fa-times"></div>'+'</div>');that.gallery_events(); }
	/**					**					*/			this.gallery_events=			function()							{	that.$viewPrint=that.$viewer.find('.viewer-print');that.$viewReset=that.$viewer.find('.viewer-reset');that.$canvas=that.$viewer.find('.gallery-canvas');that.$footer=that.$viewer.find('.gallery-footer');that.$title=that.$viewer.find('.gallery-title');that.$button=that.$viewer.find('.gallery-button');that.$tooltip=that.$viewer.find('.gallery-tooltip');that.$list=that.$viewer.find('.gallery-list');that.$button.addClass('gallery-close');that.$viewer.css('z-index',that.options.zIndex).addClass(['gallery-fixed','gallery-fade','gallery-hide'].join(' '));$(that).after(that.$viewer);that.isBuilt=true;that.gallery_initList();that.gallery_renderList(that.index);that.$viewer.find('.galleryZoomInOut').click(function(e){e.preventDefault();that.gallery_zoom($(this).hasClass('fa fa-plus')?'+':'-');});that.$viewReset.click(function(){that.image.zoom=100;that.image.zoomwidth=that.image.resetwidth;that.image.zoomheight=that.image.resetheight;that.image.top=
	/**					**					*/																					that.image.resettop;that.image.left=that.image.resetleft;that.image.width=that.image.resetwidth;that.image.height=that.image.resetheight;that.image.scaleX=1;that.image.scaleY=1;that.image.rotate=0;that.gallery_renderImage();that.gallery_tooltip('reset');});that.$viewer.find('.galleryPrevNext').click(function(){if($(this).hasClass('fa-chevron-left')){that.index--;if(that.index==-1)that.index=that.length-1;}else{that.index++;if(that.index==that.length)that.index=0;}that.gallery_renderList(that.index);that.gallery_view(that.index);});that.$viewer.find('.galleryRotateLeftRight').click(function(){that.gallery_rotate($(this).hasClass('fa-undo')?-90:90);});that.$viewer.find('.galleryFlip').click(function(){if($(this).hasClass('fa-arrows-h')){that.gallery_scale('X',-that.image.scaleX||-1);}else{that.gallery_scale('Y',-that.image.scaleY||-1);}});that.$viewer.find('.gallery-button').click(function(){that.gallery_close();});that.$viewPrint.click(function()
	/**					**					*/																					{that.gallery_print($('#viewImg').attr('src'));return true;});that.$list.find('img').each(function(index){$(this).click(function(){that.index=Number($(this).data('index'));that.gallery_renderList(Number($(this).data('index')));that.gallery_view(Number($(this).data('index')));});});$(document).bind('keydown.viewer',function(e){switch(e.which){case 37:that.$viewer.find('.fa-chevron-left').trigger('click');break;case 39:that.$viewer.find('.fa-chevron-right').trigger('click');break;case 27:that.gallery_close();break;case 38:case 107:case 40:case 109:e.preventDefault();that.gallery_zoom(e.which==38||e.which==107?'+':'-');break;case 32:e.preventDefault();that.gallery_toggle();}});that.$viewer.on('mousewheel',function(e){e.preventDefault();that.gallery_zoom(e.originalEvent.wheelDelta<0?'+':'-');}); }
	/**					**					*/			this.gallery_print=				function(img)						{	var options="toolbar=no,location=no,directories=no,menubar=no,scrollbars=yes,width="+($(window).width()*0.9)+",height="+($(window).height()*0.9),printWindow=window.open('','print',options);printWindow.document.open();printWindow.document.write('<!DOCTYPE html>'+'<html>'+'<head>'+'<title>'+$.langs['gallery-print']+'</title>'+'</head>'+'<body onload="window.focus();window.print();window.close();">'+'<img src="'+img+'" style="max-width: 100%;max-height:100%" />'+'</body>'+'</html>');printWindow.document.close();printWindow.focus(); }
	/**					**					*/			this.gallery_renderList=		function(index) 					{	var width=((that.$items.eq(index).width()+1)*that.length);that.$list.css({'width':width,'margin-left':($(window).outerWidth()/2)-(width/2)});that.$items.each(function(){$(this).removeClass('viewer-active')});that.$items.eq(index).addClass('viewer-active') }
	/**					**					*/			this.gallery_initList=			function() 							{	that.$images.each(function(i){that.$list.append('<li>'+'<img'+' src="'+that.$images[i].src+'"'+' data-index="'+i+'"'+'>'+'</li>');});that.$items=that.$list.children(); }
	/**					**					*/			this.gallery_close=				function()							{	that.$viewer.removeClass('gallery-in');setTimeout(function(){that.$viewer.css({'display':'none'});that.$body.removeClass('gallery-open');},500); }
	/**					**					*/			this.gallery_rotate=			function(degree) 					{	that.image.rotate=Number((that.image.rotate||0)+Number(degree));that.gallery_renderImage(); }
	/**					**					*/			this.gallery_zoom=				function(ratio)						{	var zooming=1;if(ratio=='+'&&that.image.zoom==200||ratio=='-'&&that.image.zoom==20){zooming=0;that.gallery_tooltip('limit');}if(zooming==1){if(ratio=='+'){var newWidth=that.image.zoomwidth*1.05,newHeight=that.image.zoomheight*1.05;that.image.zoom+=5;}else{var newWidth=(that.image.zoomwidth/100)*95,newHeight=(that.image.zoomheight/100)*95;that.image.zoom-=5;}that.image.zoomwidth=newWidth;that.image.zoomheight=newHeight;var viewerWidth=$(window).width(),viewerHeight=$(window).height()-that.$footer.height();that.$image.css({'width':newWidth,'height':newHeight,'margin-top':(viewerHeight-newHeight)/2,'margin-left':(viewerWidth-newWidth)/2});that.gallery_tooltip('');} }
	/**					**					*/			this.gallery_renderImage=		function() 							{	that.$image.css({width:that.image.width,height:that.image.height,marginLeft:that.image.left,marginTop:that.image.top,transform:that.gallery_getTransform(that.image)}); }
	/**					**					*/			this.gallery_view=				function(index) 					{	that.$title.html($.langs['gallery-views'].replace('#1',(index+1)).replace('#2',that.length));$item=this.$items.eq(index);$img=$item.find('img');url=$img.attr('src');this.$image=$('<img id="viewImg" src="'+url+'">');that.$canvas.html(that.$image.addClass('gallery-invisible').addClass('gallery-transitionZero'));var newImg=new Image;newImg.onload=function(){var naturalWidth=this.width,naturalHeight=this.height,viewerWidth=$(window).width(),viewerHeight=$(window).height()-that.$footer.height(),aspectRatio=naturalWidth/naturalHeight,width=viewerWidth,height=viewerHeight;if(viewerHeight*aspectRatio>viewerWidth){height=viewerWidth/aspectRatio;}else{width=viewerHeight*aspectRatio;}width=Math.min(width*0.9,naturalWidth);height=Math.min(height*0.9,naturalHeight);that.$image.css({'width':width,'height':height,'margin-top':(viewerHeight-height)/2,'margin-left':(viewerWidth-width)/2,'transform':that.gallery_getTransform
	/**					**					*/																					(that.$image),'transform':'scale(1)'});that.image={naturalWidth:naturalWidth,naturalHeight:naturalHeight,resettop:(viewerHeight-height)/2,resetleft:(viewerWidth-width)/2,resetwidth:width,resetheight:height,zoomwidth:width,zoomheight:height,zoom:100,width:width,height:height,top:(viewerHeight-height)/2,left:(viewerWidth-width)/2,scaleX:1,scaleY:1};that.gallery_renderImage();that.$image.removeClass('gallery-invisible').toggleClass('gallery-transition');};newImg.src=url; }
	/**					**					*/			this.gallery_isNumber=			function(n)							{	return typeof n==='number'&&!isNaN(n); }
	/**					**					*/			this.gallery_getTransform=		function(options) 					{	var transforms=[],rotate=options.rotate,scaleX=options.scaleX,scaleY=options.scaleY;if(that.gallery_isNumber(rotate))transforms.push('rotate('+rotate+'deg)');if(that.gallery_isNumber(scaleX)&&that.gallery_isNumber(scaleY))transforms.push('scale('+scaleX+','+scaleY+')');return transforms.length?transforms.join(' '):'none'; }
	/**					**					*/			this.gallery_scale=				function(mode,scale)				{	scaleX=mode=='X'?scale:this.image.scaleX;scaleY=mode=='X'?this.image.scaleY:scale;if(scaleY==='undefined')scaleY=scaleX;scaleX=Number(scaleX);scaleY=Number(scaleY);if(that.gallery_isNumber(scaleX))that.image.scaleX=scaleX;if(that.gallery_isNumber(scaleY))that.image.scaleY=scaleY;that.gallery_renderImage(); }
	/**					**					*/			this.gallery_tooltip=			function(text) 						{	var classes=['gallery-show','gallery-fade','gallery-transition'].join(' ');that.$tooltip.text(text==''?Math.round(that.image.zoom)+'%':$.langs['gallery-'+text]);if(!that.tooltiping){that.$tooltip.addClass(classes);that.$tooltip.addClass('gallery-in');clearTimeout(that.tooltipingShow);}that.tooltipingShow=setTimeout(function(){that.$tooltip.removeClass(classes);that.tooltiping=false;},1000); }
	/****************************************/																															
														this.init();
													});
												}